### PR TITLE
Do not require symlinks to resolve

### PR DESCRIPTION
**Pull request by blyxxyz**
If preserve-symlinks is enabled then symlinks don't have to resolve to be added to the package. This is e.g. useful for aliases for executables, where the symlink is in a different directory before being copied.

### CODE REVIEW

**Comment by kornelski** [comment]
I would prefer to minimize amount of configurations users need to know about. Would it be possible to have some smart defaults for this?

For example, if symlink resolves to a file, then copy the file. If the symlink is "broken", then copy the symlink itself (possibly with a warning that suggests setting the config flag to silence the warning).

**Comment by blyxxyz** [comment]
Hm. That's a bit tricky because it means the behavior changes if the symlink starts resolving.

Maybe it should still be an error, just a more informative one with that same suggestion?

**Comment by kornelski** [comment]
Yeah, but what are the chances that it will start resolving?

Error with help text is a good idea.

**Review by kornelski — CHANGES_REQUESTED** [review]
I'd prefer an implicit default behavior

**Pull request closed without merging**
