### PR TITLE
Imp/fast

### LINKED ISSUE #108: Allow to specify the desired compression level
It seems the compression level is set to 9 (the highest possible) by default. Unfortunately for really big binaries (or debug info packages), this may result in the very long run (in my case it routinely takes over 10 minutes in one of my CI pipelines). It could be useful to be able to set the desired compression level externally. For example via a command line or environment variable.

### PR DESCRIPTION
**Pull request by imp**
Fixes #108 

So, here is my take on this. Each commit incrementally gets us to the goal but can be dropped if found controversial. In my tests, `zopfli`-based gz compression has just hung on large (> 1GB) executables. `flate2` on the other hand works like a charm (and **is** fast).

### CODE REVIEW

**Comment by kornelski** [comment]
I'll resolve the conflicts

**Comment by kornelski** [comment]
Good idea with default level 6.

**Comment by kornelski** [comment]
I've picked the first two commits, which add fast flag, and made it use LZMA level 1 for the fast option.

LZMA lev 1 is faster than the default flate2 compression level.

While flate2 with level 1 would be even faster, it doesn't compress as well as Zopfli in the "slow" mode.

**Comment by imp** [comment]
This is not what I am getting in my tests, but the difference is small enough to not matter that much. Thanks for merging it!

**Pull request closed without merging**
